#!/usr/bin/env node
import http from "node:http";
import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { authorized, loadOrCreateKey } from "./lib/auth.mjs";

const root = path.dirname(fileURLToPath(import.meta.url));
const options = {};
for (let i = 2; i < process.argv.length; i += 1) { const item = process.argv[i]; if (item.startsWith("--")) options[item.slice(2)] = process.argv[i + 1]?.startsWith("--") ? true : process.argv[++i]; }
const port = Number(options.port || 8878);
const dataDir = path.resolve(String(options["data-dir"] || path.join(root, "..", "data")));
const key = await loadOrCreateKey(path.join(dataDir, "control_signing.key"));
const grantsPath = path.join(dataDir, "control_grants.json");
const grants = new Map(Object.entries(JSON.parse(await fs.readFile(grantsPath, "utf8").catch((error) => error.code === "ENOENT" ? "{}" : Promise.reject(error)))));

const scopes = new Set(["status:read", "jobs:read", "jobs:execute", "jobs:cancel", "files:read", "files:write", "tasks:read", "tasks:execute", "tasks:cancel", "tasks:delete"]);
function json(response, status, value) { const body = JSON.stringify(value); response.writeHead(status, { "content-type": "application/json; charset=utf-8", "content-length": Buffer.byteLength(body), "cache-control": "no-store" }); response.end(body); }
async function save() { await fs.mkdir(dataDir, { recursive: true }); const tmp = `${grantsPath}.tmp`; await fs.writeFile(tmp, JSON.stringify(Object.fromEntries(grants)), { mode: 0o600 }); await fs.rename(tmp, grantsPath); }
async function body(request) { let raw = ""; for await (const chunk of request) { raw += chunk; if (raw.length > 32768) throw new Error("request body is too large"); } const value = JSON.parse(raw || "{}"); if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("request body must be an object"); return value; }
function validateBinding(binding) { if (!binding || typeof binding !== "object" || typeof binding.host !== "string" || !binding.host.trim() || binding.host.length > 255 || !Number.isInteger(binding.port) || binding.port < 1 || binding.port > 65535 || typeof binding.username !== "string" || !binding.username || binding.username.length > 64 || typeof binding.fingerprint !== "string" || !/^SHA256:[A-Za-z0-9+/]{20,}={0,2}$/.test(binding.fingerprint)) throw new Error("binding requires a valid host, port, username, and SHA256 fingerprint"); return { host: binding.host.trim(), port: binding.port, username: binding.username, fingerprint: binding.fingerprint }; }
function createGrant(binding, requested, ttl = 86400) { const checked = validateBinding(binding); if (!Array.isArray(requested) || !requested.length || requested.some((scope) => !scopes.has(scope))) throw new Error("unsupported scope"); if (!Number.isInteger(ttl) || ttl < 60 || ttl > 86400) throw new Error("ttl_seconds must be between 60 and 86400"); const id = `grant-${crypto.randomBytes(18).toString("base64url")}`; const claims = { jti: id, binding: checked, scopes: [...new Set(requested)].sort(), exp: Math.floor(Date.now() / 1000) + ttl }; const encoded = Buffer.from(JSON.stringify(claims)).toString("base64url"); const signature = crypto.createHmac("sha256", key).update(encoded).digest("base64url"); grants.set(id, { binding: checked, scopes: claims.scopes, exp: claims.exp, revoked: false }); return { grant_id: id, token: `${encoded}.${signature}`, expires_at: claims.exp, scopes: claims.scopes }; }
function activeGrant(binding) { const checked = validateBinding(binding); return [...grants.entries()].filter(([, grant]) => !grant.revoked && grant.exp > Date.now() / 1000 && JSON.stringify(grant.binding) === JSON.stringify(checked)).sort((a, b) => b[1].exp - a[1].exp)[0] || null; }
function verifyToken(token, binding, scope) { if (typeof token !== "string" || token.split(".").length !== 2) throw new Error("invalid capability token"); const [encoded, supplied] = token.split("."); const expected = crypto.createHmac("sha256", key).update(encoded).digest("base64url"); const suppliedBuffer = Buffer.from(supplied); const expectedBuffer = Buffer.from(expected); if (suppliedBuffer.length !== expectedBuffer.length || !crypto.timingSafeEqual(suppliedBuffer, expectedBuffer)) throw new Error("invalid capability signature"); let claims; try { claims = JSON.parse(Buffer.from(encoded, "base64url").toString("utf8")); } catch { throw new Error("invalid capability claims"); } const checked = validateBinding(binding); const grant = grants.get(claims.jti); if (!grant || grant.revoked || grant.exp <= Date.now() / 1000 || claims.exp !== grant.exp || JSON.stringify(grant.binding) !== JSON.stringify(checked) || JSON.stringify(claims.binding) !== JSON.stringify(checked)) throw new Error("capability is expired, revoked, or bound to another session"); if (scope != null && (!scopes.has(scope) || !grant.scopes.includes(scope))) throw new Error("capability does not include the requested scope"); return claims; }
async function handle(request, response) { const url = new URL(request.url, `http://127.0.0.1:${port}`); if (request.method === "GET" && url.pathname === "/api/v1/health") return json(response, 200, { ok: true, mode: "authorization-control-plane" }); if (!authorized(request, key, `127.0.0.1:${server.address()?.port || port}`)) return json(response, 403, { error: "control-plane authorization required" }); if (request.method !== "POST") return json(response, 405, { error: "method not allowed" }); const data = await body(request); if (url.pathname === "/api/v1/grants") { const result = createGrant(data.binding, data.scopes, data.ttl_seconds); await save(); return json(response, 201, result); } if (url.pathname === "/api/v1/authorize") { const grant = activeGrant(data.binding); return json(response, 200, { authorized: Boolean(grant), grant: grant ? { grant_id: grant[0], ...grant[1] } : null }); } if (url.pathname === "/api/v1/verify") return json(response, 200, { authorized: true, claims: verifyToken(data.token, data.binding, data.scope) }); if (url.pathname === "/api/v1/revoke") { const grant = grants.get(data.grant_id); if (!grant) return json(response, 404, { error: "unknown grant" }); grant.revoked = true; await save(); return json(response, 200, { revoked: true }); } return json(response, 404, { error: "not found" }); }
const server = http.createServer((request, response) => handle(request, response).catch((error) => json(response, 400, { error: error.message || "control-plane error" })));
server.listen(port, "127.0.0.1", () => process.stdout.write(`${JSON.stringify({ ok: true, mode: "authorization-control-plane", url: `http://127.0.0.1:${server.address().port}` })}\n`));
process.on("SIGTERM", () => server.close(() => process.exit(0))); process.on("SIGINT", () => server.close(() => process.exit(0)));
